### ISSUE TITLE
[은나] 191218. To-Do

### ISSUE THREAD

**Issue by EunnaYoo** [sichan0107/final_project#5]
**[ Front ]**
~~1. Encouraged 페이지 구축~~
~~2. Html → JSP 변환~~
3. Spring Boot Entity 설정

**Comment by Hyunmin1992** [comment]
DL4J

**Comment by dev-Jini** [comment]
1. 텍스트 검색 boolquery 수정
2. 세부 효능 데이터 찾기 -> 크롤링 -> 전처리
3. 검색창 template 찾아보기( + 시간 되면)

**Comment by sichan0107** [comment]
[DL]

1.  Base code를 이용해 자체 데이터셋 구동 : matterport's github (Mask RCNN)

**Comment by EunnaYoo** [comment]
1-1) 척척약사 페이지 About 삽입

**Comment by EunnaYoo** [comment]
> **[ Front ]**
> 
> 1. Encouraged 페이지 구축
> 2. Html → JSP 변환
> 3. Spring Boot Entity 설정

1-1) 척척약사 페이지 About 삽입
